export const pointsOfInterest = [
  {
    id: "0",
    name: "Northern Terminus",
    northToSouth: 0,
    southToNorth: 297.8,
    type: "campsite",
    size: "M",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "1",
    name: "Otter Lake Road Trailhead",
    northToSouth: 1.2,
    southToNorth: 296.6,
    type: "trailhead",
    size: "M",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0.7,
    overnightParking: "unknown",
  },
  {
    id: "2",
    name: "Andy Creek",
    northToSouth: 2.9,
    southToNorth: 294.9,
    type: "campsite",
    size: "S",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "3",
    name: "Andy Lake Road Trailhead",
    northToSouth: 4.5,
    southToNorth: 293.3,
    type: "trailhead",
    size: "M",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "4",
    name: "Jackson Creek",
    northToSouth: 8,
    southToNorth: 289.8,
    type: "campsite",
    size: "S",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "5",
    name: "Jackson Lake road Trailhead",
    northToSouth: 9.4,
    southToNorth: 288.4,
    type: "trailhead",
    size: "M",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0.1,
    overnightParking: "unknown",
  },
  {
    id: "6",
    name: "Caribou Pond",
    northToSouth: 11.3,
    southToNorth: 0,
    type: "campsite",
    size: "S",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "7",
    name: "Arrowhead Trail Trailhead",
    northToSouth: 14.1,
    southToNorth: 283.7,
    type: "trailhead",
    size: "M",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0.1,
    overnightParking: "unknown",
  },
  {
    id: "8",
    name: "North Carlson Pond",
    northToSouth: 15,
    southToNorth: 282.8,
    type: "campsite",
    size: "M",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "9",
    name: "Hazel",
    northToSouth: 19.9,
    southToNorth: 277.9,
    type: "campsite",
    size: "S",
    unreliableWater: true,
    waterNotes: "none",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "10",
    name: "North Camp 20 Road Trailhead",
    northToSouth: 22,
    southToNorth: 275.8,
    type: "trailhead",
    size: "M",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 1.7,
    overnightParking: "unknown",
  },
  {
    id: "11",
    name: "South Camp 20 Road Trailhead",
    northToSouth: 23.7,
    southToNorth: 274.1,
    type: "trailhead",
    size: "M",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 1.7,
    overnightParking: "unknown",
  },
  {
    id: "12",
    name: "Judge C.R. Magney State Park Trailhead",
    northToSouth: 28.3,
    southToNorth: 269.5,
    type: "trailhead",
    size: "M",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "13",
    name: "Northwest Little Brule River",
    northToSouth: 31.1,
    southToNorth: 266.7,
    type: "campsite",
    size: "S",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "14",
    name: "North Little Brule River",
    northToSouth: 31.6,
    southToNorth: 266.2,
    type: "campsite",
    size: "M",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "15",
    name: "South Little Brule River",
    northToSouth: 32,
    southToNorth: 265.8,
    type: "campsite",
    size: "S",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "16",
    name: "Dadunce River",
    northToSouth: 37.2,
    southToNorth: 260.6,
    type: "campsite",
    size: "S",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "17",
    name: "Kadunce River State Wayside Trailhead",
    northToSouth: 37.4,
    southToNorth: 260.4,
    type: "trailhead",
    size: "M",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0.7,
    overnightParking: "unknown",
  },
  {
    id: "18",
    name: "West Fork Kadunce",
    northToSouth: 37.7,
    southToNorth: 260.1,
    type: "campsite",
    size: "M",
    unreliableWater: true,
    waterNotes: "none, 0.3mi north or south",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "19",
    name: "Crow Creek",
    northToSouth: 38,
    southToNorth: 259.8,
    type: "campsite",
    size: "M",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "20",
    name: "Kimball Creek",
    northToSouth: 39.2,
    southToNorth: 258.6,
    type: "campsite",
    size: "S",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "21",
    name: "Cliff Creek",
    northToSouth: 41.7,
    southToNorth: 256.1,
    type: "campsite",
    size: "L",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "22",
    name: "Durfee Creek",
    northToSouth: 42.8,
    southToNorth: 255,
    type: "campsite",
    size: "L",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "23",
    name: "Woods Creek",
    northToSouth: 45.2,
    southToNorth: 252.6,
    type: "campsite",
    size: "M",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "24",
    name: "Lindskog Road Trailhead",
    northToSouth: 45.7,
    southToNorth: 252.1,
    type: "trailhead",
    size: "M",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "25",
    name: "East Devil Track River",
    northToSouth: 47.4,
    southToNorth: 250.1,
    type: "campsite",
    size: "S",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "26",
    name: "West Devil Track River",
    northToSouth: 47.8,
    southToNorth: 250,
    type: "campsite",
    size: "L",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "27",
    name: "Pincushion Mountain Trailhead",
    northToSouth: 50.5,
    southToNorth: 247.3,
    type: "trailhead",
    size: "M",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "28",
    name: "Cook County Road 6 Trailhead",
    northToSouth: 55.6,
    southToNorth: 242.2,
    type: "trailhead",
    size: "M",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0.1,
    overnightParking: "unknown",
  },
  {
    id: "29",
    name: "North Bally Creek Pond",
    northToSouth: 58.4,
    southToNorth: 239.4,
    type: "campsite",
    size: "S",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "30",
    name: "South Bally Creek Pond",
    northToSouth: 58.6,
    southToNorth: 239.2,
    type: "campsite",
    size: "M",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "31",
    name: "Bally Creek Road Trailhead",
    northToSouth: 58.7,
    southToNorth: 239.1,
    type: "trailhead",
    size: "M",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "32",
    name: "Sundling Creek",
    northToSouth: 59.8,
    southToNorth: 238,
    type: "campsite",
    size: "M",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "33",
    name: "Sundling Creek Trailhead",
    northToSouth: 59.8,
    southToNorth: 238,
    type: "trailhead",
    size: "M",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0.7,
    overnightParking: "unknown",
  },
  {
    id: "34",
    name: "North Cascade River",
    northToSouth: 63.3,
    southToNorth: 234.5,
    type: "campsite",
    size: "L",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "35",
    name: "Cook County Road 45 Trailhead",
    northToSouth: 64.2,
    southToNorth: 233.6,
    type: "trailhead",
    size: "M",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0.3,
    overnightParking: "unknown",
  },
  {
    id: "36",
    name: "Cut Log",
    northToSouth: 65.7,
    southToNorth: 232.1,
    type: "campsite",
    size: "S",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "37",
    name: "Big White Pine",
    northToSouth: 66.2,
    southToNorth: 231.6,
    type: "campsite",
    size: "S",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "38",
    name: "Cascade River Wayside Trailhead",
    northToSouth: 67.2,
    southToNorth: 230.6,
    type: "trailhead",
    size: "M",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0.6,
    overnightParking: "unknown",
  },
  {
    id: "39",
    name: "Camp Creek",
    northToSouth: 69.2,
    southToNorth: 228.6,
    type: "campsite",
    size: "L",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "40",
    name: "Spruce Creek",
    northToSouth: 72.4,
    southToNorth: 225.4,
    type: "campsite",
    size: "L",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "41",
    name: "Jonvick Creek",
    northToSouth: 74.6,
    southToNorth: 223.2,
    type: "campsite",
    size: "S",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "42",
    name: "Caribou Trail Trailhead",
    northToSouth: 76.7,
    southToNorth: 221.1,
    type: "trailhead",
    size: "M",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0.9,
    overnightParking: "unknown",
  },
  {
    id: "43",
    name: "East Lake Agnes",
    northToSouth: 76.9,
    southToNorth: 220.9,
    type: "campsite",
    size: "M",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "44",
    name: "West Lake Agnes",
    northToSouth: 77.3,
    southToNorth: 220.5,
    type: "campsite",
    size: "M",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "45",
    name: "East Poplar River",
    northToSouth: 80.2,
    southToNorth: 217.6,
    type: "campsite",
    size: "S",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "46",
    name: "West Poplar River",
    northToSouth: 80.6,
    southToNorth: 217.2,
    type: "campsite",
    size: "M",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "47",
    name: "Skil Hill Road Trailhead",
    northToSouth: 82.2,
    southToNorth: 215.6,
    type: "trailhead",
    size: "M",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0.2,
    overnightParking: "unknown",
  },
  {
    id: "48",
    name: "Mystery Mountain",
    northToSouth: 82.7,
    southToNorth: 215.1,
    type: "campsite",
    size: "L",
    unreliableWater: true,
    waterNotes: "none, 0.5 north",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "49",
    name: "East Rollins Creek",
    northToSouth: 87.1,
    southToNorth: 210.7,
    type: "campsite",
    size: "S",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "50",
    name: "West Rollins Creek",
    northToSouth: 87.1,
    southToNorth: 210.7,
    type: "campsite",
    size: "M",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "51",
    name: "Onion River Road Trailhead",
    northToSouth: 88.7,
    southToNorth: 209.1,
    type: "trailhead",
    size: "M",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "52",
    name: "Onion River Road Trailhead",
    northToSouth: 89.1,
    southToNorth: 208.7,
    type: "campsite",
    size: "L",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "53",
    name: "East Leveaux Pond",
    northToSouth: 90.3,
    southToNorth: 207.5,
    type: "campsite",
    size: "M",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "54",
    name: "West Leveaux Pond",
    northToSouth: 90.4,
    southToNorth: 207.4,
    type: "campsite",
    size: "L",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "55",
    name: "Springdale Creek",
    northToSouth: 92.6,
    southToNorth: 205.2,
    type: "campsite",
    size: "M",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "56",
    name: "Sawbill Trail Trailhead",
    northToSouth: 94.2,
    southToNorth: 203.6,
    type: "trailhead",
    size: "M",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "57",
    name: "Temperance River Wayside Trailhead",
    northToSouth: 98.8,
    southToNorth: 199,
    type: "trailhead",
    size: "M",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0.2,
    overnightParking: "unknown",
  },
  {
    id: "58",
    name: "Temperance River Road Trailhead",
    northToSouth: 99.6,
    southToNorth: 198.2,
    type: "trailhead",
    size: "M",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "59",
    name: "Skou Road Trailhead",
    northToSouth: 101.5,
    southToNorth: 196.3,
    type: "trailhead",
    size: "M",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 1.4,
    overnightParking: "unknown",
  },
  {
    id: "60",
    name: "South Cross River",
    northToSouth: 101.5,
    southToNorth: 196.3,
    type: "campsite",
    size: "M",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "61",
    name: "North Cross River",
    northToSouth: 101.6,
    southToNorth: 196.2,
    type: "campsite",
    size: "S",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "62",
    name: "The Ledge",
    northToSouth: 102.2,
    southToNorth: 195.6,
    type: "campsite",
    size: "S",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "63",
    name: "The Falls",
    northToSouth: 103,
    southToNorth: 194.8,
    type: "campsite",
    size: "S",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "64",
    name: "Fredenberg Creek",
    northToSouth: 104.8,
    southToNorth: 193,
    type: "campsite",
    size: "L",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "65",
    name: "Cook County Road 1 Trailhead",
    northToSouth: 106.4,
    southToNorth: 191.4,
    type: "trailhead",
    size: "M",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "66",
    name: "Dyers Creek",
    northToSouth: 107.7,
    southToNorth: 190.1,
    type: "campsite",
    size: "M",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "67",
    name: "Sugarloaf Pond",
    northToSouth: 111.1,
    southToNorth: 186.7,
    type: "campsite",
    size: "M",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "68",
    name: "Sugarloaf Road Trailhead",
    northToSouth: 112,
    southToNorth: 185.8,
    type: "trailhead",
    size: "M",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "69",
    name: "Cystal Creek",
    northToSouth: 113.5,
    southToNorth: 184.3,
    type: "campsite",
    size: "M",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "70",
    name: "East Caribou River",
    northToSouth: 114.7,
    southToNorth: 183.1,
    type: "campsite",
    size: "L",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "71",
    name: "Caribou Falls State Wayside Trailhead",
    northToSouth: 114.7,
    southToNorth: 183.1,
    type: "trailhead",
    size: "M",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0.7,
    overnightParking: "unknown",
  },
  {
    id: "72",
    name: "West Caribou River",
    northToSouth: 114.8,
    southToNorth: 183,
    type: "campsite",
    size: "S",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "73",
    name: "Horseshoe Ridge",
    northToSouth: 117.6,
    southToNorth: 180.2,
    type: "campsite",
    size: "M",
    unreliableWater: true,
    waterNotes: "unreliable",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "74",
    name: "George Crosby Manitou State Park Trailhead",
    northToSouth: 121.7,
    southToNorth: 176.1,
    type: "trailhead",
    size: "M",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "75",
    name: "Aspen Knob",
    northToSouth: 122.6,
    southToNorth: 175.2,
    type: "campsite",
    size: "S",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "76",
    name: "Blesener Creek",
    northToSouth: 124.6,
    southToNorth: 173.2,
    type: "campsite",
    size: "S",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "77",
    name: "East Branch Baptism River",
    northToSouth: 125.2,
    southToNorth: 172.6,
    type: "campsite",
    size: "S",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "78",
    name: "Sonju Lake Road Trailhead",
    northToSouth: 125.7,
    southToNorth: 172.1,
    type: "trailhead",
    size: "M",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0.1,
    overnightParking: "unknown",
  },
  {
    id: "79",
    name: "North Sonju Lake",
    northToSouth: 127,
    southToNorth: 170.8,
    type: "campsite",
    size: "M",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "80",
    name: "South Sonju Lake",
    northToSouth: 127.3,
    southToNorth: 170.5,
    type: "campsite",
    size: "L",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "81",
    name: "North Egge Lake",
    northToSouth: 130.3,
    southToNorth: 167.5,
    type: "campsite",
    size: "M",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "82",
    name: "South Egge Lake",
    northToSouth: 130.5,
    southToNorth: 167.3,
    type: "campsite",
    size: "M",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "83",
    name: "Lake County Road 7 Trailhead",
    northToSouth: 133,
    southToNorth: 164.8,
    type: "trailhead",
    size: "M",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0.3,
    overnightParking: "unknown",
  },
  {
    id: "84",
    name: "Leskinen Creek",
    northToSouth: 135.1,
    southToNorth: 162.7,
    type: "campsite",
    size: "L",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "85",
    name: "Section 13",
    northToSouth: 138.8,
    southToNorth: 159,
    type: "campsite",
    size: "M",
    unreliableWater: true,
    waterNotes: "none, 0.5 mi north or 1.1 mi south",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "86",
    name: "Lake County Road 6 Trailhead",
    northToSouth: 140.2,
    southToNorth: 157.6,
    type: "trailhead",
    size: "M",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0.2,
    overnightParking: "unknown",
  },
  {
    id: "87",
    name: "East Kenney Creek",
    northToSouth: 144.9,
    southToNorth: 152.9,
    type: "campsite",
    size: "M",
    unreliableWater: true,
    waterNotes: "unreliable",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "88",
    name: "West Kennedy Creek",
    northToSouth: 144.9,
    southToNorth: 152.9,
    type: "campsite",
    size: "M",
    unreliableWater: true,
    waterNotes: "unreliable",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "89",
    name: "Minnesota Highway 1 Trailhead",
    northToSouth: 147.2,
    southToNorth: 150.6,
    type: "trailhead",
    size: "M",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0.1,
    overnightParking: "unknown",
  },
  {
    id: "90",
    name: "Tettegouche State Park Wayside Trailhead",
    northToSouth: 148,
    southToNorth: 149.8,
    type: "trailhead",
    size: "M",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 1.2,
    overnightParking: "unknown",
  },
  {
    id: "91",
    name: "Tettegouche State Park Trailhead",
    northToSouth: 148.6,
    southToNorth: 149.2,
    type: "trailhead",
    size: "M",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0.3,
    overnightParking: "unknown",
  },
  {
    id: "92",
    name: "East Palisade Creek",
    northToSouth: 152.9,
    southToNorth: 144.9,
    type: "campsite",
    size: "L",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "93",
    name: "Bear Lake",
    northToSouth: 154.7,
    southToNorth: 143.1,
    type: "campsite",
    size: "S",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "94",
    name: "Penn Creek",
    northToSouth: 155.9,
    southToNorth: 141.9,
    type: "campsite",
    size: "L",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "95",
    name: "Penn Boulevard Trailhead",
    northToSouth: 157.9,
    southToNorth: 139.9,
    type: "campsite",
    size: "M",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0.1,
    overnightParking: "unknown",
  },
  {
    id: "96",
    name: "East Beaver River",
    northToSouth: 161.2,
    southToNorth: 136.6,
    type: "campsite",
    size: "S",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "97",
    name: "West Beaver River",
    northToSouth: 161.5,
    southToNorth: 136.3,
    type: "campsite",
    size: "S",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "98",
    name: "Lax Lake Road Trailhead",
    northToSouth: 162.2,
    southToNorth: 135.6,
    type: "trailhead",
    size: "M",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "99",
    name: "Fault Line Creek",
    northToSouth: 165.9,
    southToNorth: 131.9,
    type: "campsite",
    size: "M",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "100",
    name: "Beaver Pond",
    northToSouth: 167.3,
    southToNorth: 130.5,
    type: "campsite",
    size: "M",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "101",
    name: "Chapins Ridge",
    northToSouth: 169,
    southToNorth: 128.8,
    type: "campsite",
    size: "M",
    unreliableWater: true,
    waterNotes: "none, 0.2mi north",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "102",
    name: "Split Rock River Wayside Trailhead",
    northToSouth: 172.3,
    southToNorth: 125.5,
    type: "trailhead",
    size: "M",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0.7,
    overnightParking: "unknown",
  },
  {
    id: "103",
    name: "Southeast Split Rock River",
    northToSouth: 173.6,
    southToNorth: 124.2,
    type: "campsite",
    size: "S",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "104",
    name: "Northeast Split Rock River",
    northToSouth: 173.9,
    southToNorth: 123.9,
    type: "campsite",
    size: "L",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "105",
    name: "Northwest Split Rock River",
    northToSouth: 174.1,
    southToNorth: 123.7,
    type: "campsite",
    size: "M",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "106",
    name: "Southwest Split Rock River",
    northToSouth: 174.4,
    southToNorth: 123.4,
    type: "campsite",
    size: "M",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "107",
    name: "Split Rock River Wayside 2 Trailhead",
    northToSouth: 175.9,
    southToNorth: 121.9,
    type: "trailhead",
    size: "M",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0.5,
    overnightParking: "unknown",
  },
  {
    id: "108",
    name: "Blueberry Hill",
    northToSouth: 178.3,
    southToNorth: 119.5,
    type: "campsite",
    size: "M",
    unreliableWater: true,
    waterNotes: "Unreliable",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "109",
    name: "Gooseberry Falls State Park Visitor Center Trailhead",
    northToSouth: 182,
    southToNorth: 115.8,
    type: "trailhead",
    size: "M",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0.2,
    overnightParking: "unknown",
  },
  {
    id: "110",
    name: "Gooseberry River",
    northToSouth: 184.5,
    southToNorth: 113.3,
    type: "campsite",
    size: "L",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "111",
    name: "Middle Gooseberry River",
    northToSouth: 185.3,
    southToNorth: 112.5,
    type: "campsite",
    size: "S",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "112",
    name: "East Gooseberry River",
    northToSouth: 185.4,
    southToNorth: 112.4,
    type: "campsite",
    size: "S",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "113",
    name: "West Gooseberry River",
    northToSouth: 186.3,
    southToNorth: 111.5,
    type: "campsite",
    size: "M",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "114",
    name: "Crow Valley",
    northToSouth: 189.5,
    southToNorth: 108.3,
    type: "campsite",
    size: "M",
    unreliableWater: true,
    waterNotes: "Unreliable",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "115",
    name: "W. Castle Danger Road Trailhead",
    northToSouth: 190.7,
    southToNorth: 107.1,
    type: "trailhead",
    size: "M",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
  {
    id: "116",
    name: "Lake County Road 301 Trailhead",
    northToSouth: 196.7,
    southToNorth: 101.1,
    type: "trailhead",
    size: "M",
    unreliableWater: false,
    waterNotes: "",
    distanceToParking: 0,
    overnightParking: "unknown",
  },
];
